### ISSUE TITLE
Describing input control data when running ChromHMM

### ISSUE THREAD

**Issue by avilella** [jernst98/ChromHMM#10]
Hi, I am experimenting with different options in ChromHMM after reading the Nature Protocols paper from late 2017. In the paper, it says:

"ChromHMM can use input control data, such as those produced by mapping whole-cell extracts or IgG ChIP data. Control data provide information on local background signal levels, which ChromHMM can use to adjust binarization thresholds locally instead of having a uniform threshold genom wide. ChromHMM can also use control data as an additional model feature".

I am running ChromHMM with datasets of different tissue types where there is essentially one type of pulldown, which I label as "pull" below, and then the Input data equivalent to IgG ChIP, which I label "Input". See below:

```
D0004AD	Input	CEG66-107-4IC_S27_L00.bml.GRCh38.karyo.deduplicated.bam
D0016AP	pull	CEG66-107-8PC_S8_L00.bml.GRCh38.karyo.deduplicated.bam
D0004AD	pull	CEG66-107-4PC_S4_L00.bml.GRCh38.karyo.deduplicated.bam
D0012AL	pull	CEG66-112-16PC_S16_L00.bml.GRCh38.karyo.deduplicated.bam
D0011AK	Input	CEG66-112-15IC_S38_L00.bml.GRCh38.karyo.deduplicated.bam
D0005AE	pull	CEG66-107-5PC_S5_L00.bml.GRCh38.karyo.deduplicated.bam
D0002AB	pull	CEG66-107-2PC_S2_L00.bml.GRCh38.karyo.deduplicated.bam
D0023AW	Input	CEG66-117-23IC_S46_L00.bml.GRCh38.karyo.deduplicated.bam
[...]
```
I have successfully run this with subsets of my data, and it works well. I use:

```
java -mx$java_mem -jar $chromhmm BinarizeBam $genome_file $dir $listfile $binariesdir

and later on:

unset DISPLAY && java -mx$java_mem -jar $chromhmm LearnModel -s 1 -p $threads -nobrowser $binariesdir $modelsdir $num_states $assembly
```
It gives me states that, when inspected via the browser, seem to make sense: e.g. when there is no enrichment in the pulldowns, it associates one state to it, when there is, it associates one or more states to it, depending on the $num_states I use as a parameter.

But I want to confirm that I am letting ChromHMM know that "Input" in my second column corresponds to the IgG ChIP data equivalent, in case I am currently running it suboptimally and there is a better way of handling my datasets (1 mark, 1 input, several tissues).

The controls are relatively flat except for usual overpileups from Illumina sequencing. My understanding is that I should use option A: Treat controls as an additional feature.

Any thoughts? Are my options the correct one? Should I change them? Should I use the "Multiple cell types with stacking features"labeling described in the Nature protocols paper? E.g.
```
[...]
genome D0002AB_pull file2
genome D0004AD_Input file3
[...]
```

**Comment by jernst98** [comment]
Hi,

ChromHMM does not know that "Input" in your second column corresponds to IgG ChIP data equivalent. In this case it is treated as any other feature. If your input is flat except for pile-ups artifacts then it can make sense to use input this way way and you should be suspicious of any location assigned to a state with a high emission for input. The other option is to list the Input files in the fourth column and then the features are binarized locally relative to input.

Whether to use the stacking feature options for multiple cell types is a separate question depending on whether you want cell type specific annotations or one annotation of the genome based on all your data.

-Jason
