### ISSUE TITLE
Please use release tags

### ISSUE THREAD

**Issue by tillea** [jernst98/ChromHMM#11]
Hi,
the Debian Med team intends to package ChromHMM for Debian.  To make sure we will always spot your latest and greatest release it would help a lot if you would use release tags.  There are automatic tools inside Debian that will detect a new tag and we will thus know for sure what you intend to be used on user machines.
Thanks for considering, Andreas.

**Comment by jernst98** [comment]
Hi Andreas,

Yes, I can do that. I just created the first release tag for it.

Best,
-Jason
