### ISSUE TITLE
Push data files into git repository

### ISSUE THREAD

**Issue by Dybian** [jernst98/ChromHMM#12]
Hi,
Could you push data files which are available into the zip file from http://compbio.mit.edu/ChromHMM/? (i.e. ANCHORFILES, CHROMSIZES, COORDS and SAMPLEDATA_HG18 folders).
This could be useful to get a clean tarball with all files required for testing ChromHMM.

Thanks

**Comment by jernst98** [comment]
Yes, you should be able to see them now.

-Jason
