### ISSUE TITLE
Sliding window bins vs. separate bins

### ISSUE THREAD

**Issue by snaketron** [jernst98/ChromHMM#17]
Dear Developers,

I am currently using ChromHmm using custom input (BED files binarized by myself), with the major difference being that the bins are overlapping, i.e. created using a sliding window approach (e.g. bin size 200bp, slide = 50bp). Could such an input cause any problems/biases in the model learning procedure?

I am mostly interested in the effects by such a binarization on the model learning, and not as much in the neightborhood enrichment and the other annotations provided by ChromHmm.

The goal of doing this is just to increase the resolution of the analysis.

Thanks!

**Comment by jernst98** [comment]
ChromHMM already provides a level of smoothing. Technically, the ChromHMM modeling assumes the observations in each bin are independent conditioned on the hidden states, so smoothing first can be inconsistent with that, though in practice I would expect the modeling approach to be robust to limited local smoothing.

-Jason
