### ISSUE TITLE
ChromHMM state transmissions

### ISSUE THREAD

**Issue by StefanKurtenbach** [jernst98/ChromHMM#18]
I'm running ChromHMM with cells before and after knockdown of a gene, with 4 histone marks. I was playing around with the state transmission plot and am wondering whether what "From" and "To" means. I was assuming "From" means the first sample group that is defined in the config file, but it seems the other way round?

**Comment by jernst98** [comment]
The transition matrix has to do with the transitions of the HMM, which corresponds to the probability that you are in one state at a bin in the genome ('from state') of being in the 'to state' at the next the bin in the genome. It is not related to comparing cell types.
