### ISSUE TITLE
NullPointerException in ConvertGeneTable 

### ISSUE THREAD

**Issue by retropc66** [jernst98/ChromHMM#19]
I'm trying to create a gene annotation for the Gallus gallus 5.0 assembly, but getting a NullPointerException.

Command:

```
 java -Xmx8G -jar <path_to>/ChromHMM.jar ConvertGeneTable -gzip
 -l <path_to>/Gallus_gallus.Gallus_gallus-5.0.dna.toplevel.fa.fai <path_to>/gg5_ucsc_genome.txt gg5 gg5

```

Error returned is:

```
Exception in thread "main" java.lang.NullPointerException
	at edu.mit.compbio.ChromHMM.ConvertGeneTable.convertGeneTableToAnnotations(ConvertGeneTable.java:199)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13080)

```

Line 199 of ConvertGeneTable.java is:

`	    int nchromlength =((Integer) hmlengths.get(szchrom)).intValue();
`

I don't see hmlengths.get() in any of the ChromHMM source files (but perhaps imported from elsewhere?).

**Comment by jernst98** [comment]
Are all the chromosomes names in the gene annotation appearing in your chromosome length with the same naming conventions? If not, that could be the cause of the exception.

**Comment by retropc66** [comment]
Many thanks for the quick response. That was it - UCSC vs Ensembl naming
issue; I fixed the chromosome names, but didn't think about the names of
the non-chromosomal contigs. Deleted everything non-chromosomal and it
works fine.
