### ISSUE TITLE
NoSuchElementException in ConvertGeneTable

### ISSUE THREAD

**Issue by NBKingsley** [jernst98/ChromHMM#20]
I'm trying to use ConvertGeneTable on, but I'm getting a NoSuchElementException error and I can't find any information to help me troubleshoot this issue.

Command:

 java -mx1200M -jar ChromHMM.jar ConvertGeneTable pathTo/RefSeq_EquCab3_UCSC_tableSchema.txt EC3 EquCab3

The chromosome length file is saved into CHROMSIZES/ with the correct default name based on my assembly, and a previous command worked using the file. I downloaded the gene table file from UCSC directly.

Error returned is:

Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at edu.mit.compbio.ChromHMM.ConvertGeneTable.convertGeneTableToAnnotations(ConvertGeneTable.java:60)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:14406)

Help?

**Comment by jernst98** [comment]
Are you sure you downloaded the full table and not the table schema as your file naming might suggest? I tried downloading it and the command worked for me.

-Jason

**Comment by MahShaaban** [comment]
Hi @jernst98 

I am having same problem here. I suspect as you do the problem might be the `inputgenetable`. Is there away to check the table is in the required format?
I downloaded the table for mm10 from UCSC table browser, as recommended. Here is the first few lines

```bash
bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonEnds
632	NM_009826	chr1	+	6214661	6276104	6230002	6274275	24	6214661622793967e152	6214957622804963e152
1150	NM_001170641	chr1	+	74125540	74148230	74127677	74147746	12	7412554074127592e80	7412561474127721e80
1150	NM_001034060	chr1	+	74125540	74148223	74129046	74147746	12	7412554074127592e80	7412561474127721e80
1158	NR_109938	chr1	-	75180860	75192010	75192010	75192010	16	7518086075182588e112	7518193175182735e112
```

**Comment by jernst98** [comment]
The problem might be with the gene length file and not the inputgenetable. What are you using for that?
What is the command you are entering to ChromHMM? 
Are you getting the same exact exception message as above? If not can you provide it?

Note that mm10 is already included in ChromHMM so you could also use that unless you want the latest version of it.

**Comment by MahShaaban** [comment]
The command I am using and the error message are the same as above.
I am using the gene length file `CHROMSIZE/mm10.txt`.
The reason I am using `ConvertGeneTable ` with this gene table is because I want to calculate the enrichment on a subset of the genome. Is this the correct way to go about it?

**Comment by jernst98** [comment]
Did you modify CHROMSIZE/mm10.txt or are you using the same exact file as included with ChromHMM?
Are the line numbers within the exception message exactly the same as above (349, 60, 14406)?
Are the files you are providing unzipped? I realized this command is currently only supporting unzipped files, but I will fix that in the next release.

Is the segmentation file already restricted to the subset of the genome you are computing enrichments for? If so, then you do not need to subset the external annotation files further. If not and your are only subsetting the external annotations, then you would need to also compute the state enrichments for the subset of the genome you are restricting to, and divide the external annotation enrichments by those enrichments.

**Comment by MahShaaban** [comment]
I didn't modify the `CHROMSIZE/mm10.txt`

I get the following error message

> Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at edu.mit.compbio.ChromHMM.ConvertGeneTable.convertGeneTableToAnnotations(ConvertGeneTable.java:166)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:15011)

The files are unzipped.

I ran `BinarizeBam` and `LearnModel` on the original unrestricted files. From what I understand, I need to subset the annotation files if I want to calculate enrichment for a subset of the genome. Would you please expand on, or point me to an example in the documentation where I can work with a subset of external annotations.

**Comment by jernst98** [comment]
ChromHMM was assuming there was at least one more column after exonExons, which it didn't need to do. I'll fix that in the next version, but in the mean time as a work around you can simply add at least one more column at the end. The gene tables from UCSC automatically have those.

Note that it looks like you converted your exonStarts and exonEnds from a comma list of numbers to one big number, which is a separate issue.

For computing the enrichments, the question is whether you want the background to still be all regions in the segmentation file or to reflect the state frequency in your subset of the genome of interest. ChromHMM uses all regions in the segmentation file as a background. If you want the background to be the subset of genome of interest you have two options. One is remove the portion of genome not of interest from the segmentation file. The other is to compute the state enrichments for the subset of genome of interest, and then divide enrichments for the annotations in the subset of the genome, by the enrichment for the subset genome.

**Comment by MahShaaban** [comment]
This is the head of the annotation file I got from the table browser and I think it matches what's recommended in the manual. I am not sure what `exonExons` column is.
```bash
$ head -2 table.tsv
bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonEnds
632	NM_009826	chr1	+	6214661	6276104	6230002	6274275	24	6214661622793967e152	6214957622804963e152
```
I think you are correct about the comma list. I need to change that.

Got it. I think I would go with the second option. I understood that I need to calculate two types of enrichment and divide them by each other. The first is for the subset of the genome and the other for the annotation file. I am not sure however which commands should be used to calculate the first enrichment.

**Comment by jernst98** [comment]
Sorry a typo above, I meant exonEnds. ChromHMM is currently expecting there is at least one more column after exonEnds, but then ignores it.

It is the same command to compute both. You are computing the enrichment of the subset of the genome relative to the whole genome.

**Comment by MahShaaban** [comment]
Okay. I can add a column to the table.

Okay. The same command, but then what is the input for the genome subset (first run). For the second, I assume I should use the annotation file from the table browser.

**Comment by jernst98** [comment]
A bed file with the coordinates of the regions of the genome you are including in your subset.

**Comment by MahShaaban** [comment]
Got it. Thanks a lot @jernst98
