### ISSUE TITLE
ChromHMM BinarizeBam error "Permission denied"

### ISSUE THREAD

**Issue by HasseB-MAN** [jernst98/ChromHMM#23]
Hi,

I'm trying to run the script below to binarise my bam files before feeding them to ChromHMM LearnModel. 
However, I keep getting the following error:
`/var/spool/torque/mom_priv/jobs/378907.SC: line 18: /lmod/apps/chromhmm/1.19/CHROMSIZES/hg38.txt: Permission denied` .

I've tried to copy the chromsizes file to my working directory, which did not help. Then I used a completely unrelated chromsizes file, which I had previously used for a different analysis, and I still got the error "Permission denied". To me, that indicates this is either a bug or an error message that actually means something else is going wrong. 

If anyone has any idea why this might be happening, that would be greatly appreciated.

Thank you!
```

cd $PBS_O_WORKDIR

ml apps/chromhmm/1.19

#mkdir chromHMM_out_binary

java -mx7000M -jar /lmod/apps/chromhmm/1.19/ChromHMM.jar BinarizeBam -paired \
/lmod/apps/chromhmm/1.19/CHROMSIZES/hg38.txt \
$PBS_O_WORKDIR \
chromHMM_table \
./chromHMM_out_binary
```

**Comment by jernst98** [comment]
I would try putting all your arguments to ChromHMM on the same line.
It looks like your script might be trying to run /lmod/apps/chromhmm/1.19/CHROMSIZES/hg38.txt as an executable.
