### ISSUE TITLE
"flankwidthcontrol" in Preprocess

### ISSUE THREAD

**Issue by zhangnan0107** [jernst98/ChromHMM#25]
The ChromHMM manual said that `flankwidthcontrol` is used to compute **average control counts** for all bins within x-w and x+w for the xth bin, however, the **sum of counts** rather than average counts is calculated in the code (`windowSumGrid` method in `Preprocessing` class, see the following picture).

Manual:
![image](https://user-images.githubusercontent.com/34366426/86571095-7f079800-bfa3-11ea-895e-3f90cf727f11.png)

Code:
![image](https://user-images.githubusercontent.com/34366426/86570640-d3f6de80-bfa2-11ea-82ed-21281df9929e.png)

So I am wondering which one is actually used? It seems that average value is more reasonable. Maybe the mean counts is computed somewhere else?

Thanks
Nan

**Comment by jernst98** [comment]
They end up being equivalent for determining the binarization threshold based on how the values are used in
determineMarkThresholdsFromBinnedDataArrayAgainstControl

Best,
-Jason
