### ISSUE TITLE
Why is 'binarizeBed -peaks' not recommended for broad peaks?

### ISSUE THREAD

**Issue by eregenyi** [jernst98/ChromHMM#29]
Dear jernst98,

I would like to create a chromatin state annotation using publicly available chip data, e.g. on blueprint or roadmaps. The raw data is only available after some bureaucracy, but the enriched (peak) regions are freely downloadable. I saw you can use binarizeBed with the -peaks flag to have chromHMM handle the input bed files as peak files, however, according to the manual, this is not recommended for broad peaks. 
Why is `binarizeBed -peaks` not recommended for broad peaks? How would it affect the results? 

Thank you for your answers,

Best

**Comment by jernst98** [comment]
This is discussed in the ChromHMM protocols paper (https://www.nature.com/articles/nprot.2017.124).
ChromHMM already considers spatial information, and when you give it broad peaks some of the states
ChromHMM discovers might correspond to combination of marks that do not actually co-occur at the finer
resolution ChromHMM uses.

How much of issue this is might depend on how broad your peaks actually are. 
Also if you have access to the position of the aligned reads or the signal even without the
raw reads you have other options.
