### ISSUE TITLE
How are paired-end reads handled?

### ISSUE THREAD

**Issue by quantumdot** [jernst98/ChromHMM#3]
Does `ChromHMM` recognize paired-end reads, and if so, how are paired-end reads handled during the "binarization" process? How are the parameters to `BinarizeBam` affected by paired-end data, in particular the `-center`, `-e`, `-n`, `-s` parameters? 

Is it recommended in this case to first convert PE BAM files into BED/BEDPE format where the bed entry refers to the entire sequenced fragment?

Thanks

**Comment by ernstlab** [comment]
The BinarizeBam of ChromHMM iterates over all SAM records in bam files, taking the alignment start and end positions of each record. It does not do anything special for paired end reads. If that is not the desired behavior for your case, but you can produce the desired behavior by generating a bed file and then applying BinarizeBed, then that is recommended.

**Comment by jernst98** [comment]
In v1.15 of ChromHMM, I added the option '-paired' to BinarizeBam which handles paired-end reads present in the bam file. It assigns the read to the middle of pair of reads based on the insert size for the pair. If the '-paired' option is present then '-center', '-n', and '-peaks' parameters cannot be used, but -e and -s can still be used as normal.

**Comment by YichaoOU** [comment]
Hi Jason,

If the bam files folder contains both single-end and paired-end bam files, adding `-paired` option will apply to every file?

Thanks,
Yichao

**Comment by jernst98** [comment]
Hi Yichao,

Yes, but as of version 1.18 I added the command MergeBinary which allows you to merge binarized files. This way you can binarize subsets of marks with different options and then merge them together with MergeBinary.

Best,
-Jason

**Comment by jernst98** [comment]
The '-mixed' flag added in version 1.23 will decide on a read by read basis to treat the read as single end or paired end.
