### ISSUE TITLE
Model fit and uncertainity of the estimates

### ISSUE THREAD

**Issue by MahShaaban** [jernst98/ChromHMM#30]
Hi @jernst98 

I would like to ask if there is a way to quantify
-  how well the model constructed by ChromHMM fits the data
-  and, the uncertainity of the estimated probabilities (emission/transmissions)

**Comment by jernst98** [comment]
ChromHMM outputs the model log-likelihood in the model file.
There is no explicit uncertainty estimate of the emission/transmission probabilities, but
you can learn models on different subsets of the genome or from different random initializations
(with '-init random' flag) and evaluate to what extent the emission parameters of these models
correlate with the emission parameters of a reference model with the CompareModels command.

-Jason

**Comment by MahShaaban** [comment]
Okay. Great.
I would be greatful if you could help me understand the contents of the model file better, since it seems like a key to answer my question.
Here is the file [model_3.txt](https://github.com/jernst98/ChromHMM/files/5218280/model_3.txt) which I got from running `LearnModel` on the sample data provided in the repo and with `-numstates 3`.

I assume the log-likehood of transitions and emissions are the ones indicated by transitionprobs and emissionprobs. I am not sure however what the first 4 lines are.

I used `CompareModels` to construct models with different numbers of states and chose the best fit. The only way I could think of to choose is to increase the number of states by 1, until all the states are highly correlated with the states in the previous run.

If I understand correctly, you suggest using `-init random` in multiple iterations of the model using the same number of states and correlating the emission parameters. In this case, 
- Which values should be compared? The parameters in `emisison_#.txt` or the likelihoods in `model_#.txt`.
- What would be the criteria for choosing? Or I could just look for the values that the models converge upon

Thanks

**Comment by jernst98** [comment]
Except for the first line of the model file, the rest of the lines have the actual parameter values of the initial probabilities, emission probabilities, and transition probabilities. The fourth value of the first line is the log-likelihood of the model fit to the data.

CompareModels is run with the emission files. You can run CompareModels with different number of states, but I was making two additional suggestions if you wanted to evaluate the stability of specific model parameters. One was to learn models on different subset of the genome and the other from different initializations. Note that ChromHMM by default has its own model parameter initialization strategy that is not random.

If you are trying to CompareModels to help guide the selection of number of states, one way to use it is if you can identify specific states in a larger model that you want any smaller model to capture, and then use that to set a lower bound on the number of states if models of all numbers of states below that number have low correlation with a state of interest.

**Comment by MahShaaban** [comment]
Thanks @jernst98 This was very helpful.
