### ISSUE TITLE
Applying segmentation analysis to ChIP-seq data from DNA binding proteins

### ISSUE THREAD

**Issue by MahShaaban** [jernst98/ChromHMM#31]
Hi @jernst98 
I would like to ask whether it's possible, at least in priniciple, to apply `ChromHMM` to ChIP-seq data of transcription factors or other DNA binding proteins?

**Comment by jernst98** [comment]
Yes. Some of the models we have published before have CTCF. Note that if all the inputs have very punctate signal you may not see a benefit from the use of an HMM.

**Comment by MahShaaban** [comment]
Right. I have see CTCF used in some of your publications.
Would you recommend any modifications to the standard workflow in this case? For example, would the use of a small bin size say (50bp) improve the performance of the model or medigate the punctate signal situation?
Thanks a lot @jernst98

**Comment by jernst98** [comment]
I don't have specific recommendations. You can try adjusting the bin size for your application if desired, but note that if you make it too small you may not get meaningful binarizations. My point was if all your data is from point sources there might be less motivation for using an HMM as compared to clustering the point source positions directly.

**Comment by MahShaaban** [comment]
Got it. Thanks.
