### ISSUE TITLE
ChromHMM v1.21 errors: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by AdrijaK** [jernst98/ChromHMM#33]
Hi there, 

I am using ChromHMM conda version which was downloaded like this: 
```bash
conda create -n chromhmm
conda activate chromhmm
conda install --yes -c bioconda chromhmm 
```

Then I converted all input files from bam to bed 
```bash
bedtools bamtobed -i input.bam > output.bed
```

And finally ran ChromHMM.sh BinarizeBed with default options
```bash
ChromHMM.sh BinarizeBed -b 200 GRCm38.genome $PWD/bed $PWD/cellmarkfiletable.tsv $PWD/binarized_bed
```

However, I got this error message:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at edu.mit.compbio.ChromHMM.Preprocessing.makeBinaryDataFromBed(Preprocessing.java:1027)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13054)
```

Versions: 
**bedtools**:
v2.29.2

**Java**:
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)

**chromHMM**:
This is Version 1.21 of ChromHMM (c) Copyright 2008-2012 Massachusetts Institute of Technology

**Memory/CPUs available**:
MemTotal:       1044135232 kB
MemFree:        214513088 kB
MemAvailable:   970925604 kB
Cached:         742086360 kB
SwapCached:            0 kB
SwapTotal:       6292476 kB
SwapFree:        6292476 kB
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Socket(s):             2

I am not entirely familiar with java memory management yet, but is there a way to manage the java.lang.OutOfMemoryError and wasnt the ChromHMM.sh  supposed to manage that automatically? 

Thanks! 

Best regards, 
Adrija

**Comment by jernst98** [comment]
I wasn't involved in setting up the conda ChromHMM package, but it looks like you can increase the amount of memory ChromHMM has access to with the -Xmx flag immediately after ChromHMM.sh see 
https://bioconda-recipes-demo.readthedocs.io/en/docs/recipes/chromhmm/README.html

Also note ChromHMM has a BinarizeBam option, if you want to avoid converting your bed files to bam files.

**Comment by AdrijaK** [comment]
Thanks! Adding -Xmx4000M seems to be working:

```
ChromHMM.sh -Xmx4000M BinarizeBed -b 200 GRCm38.genome $PWD/bed $PWD/cellmarkfiletable.tsv $PWD/binarized_bed
```

Also noted BinarizeBam option.
