### ISSUE TITLE
Credible interval of fold-enrichment (OverlapEnrichment functionality)

### ISSUE THREAD

**Issue by snaketron** [jernst98/ChromHMM#34]
Dear developer,

the function OverlapEnrichment computes fold-enrichment for each combination of state and external annotation.

Would it be possible to obtain e.g. 95% confidence intervals or credible intervals of the fold-enrichment? 

P.S. Any idea how this functionality might be expanded (in case not yet available)? 
Given independent and identically distributed observations (here genomic bins with chromatin states), I would have applied bootstrapping with replacement, however, here we have dependent observations. 

Best

**Comment by jernst98** [comment]
If you run OverlapEnrichment with the '-center' flag, then ChromHMM will only use the center base for each external coordinate interval in computing enrichments thus reducing spatial dependencies. From the ChromHMM output there should be enough information to derive binomial based confidence intervals. This will be an approximation since the spatial dependencies aren't completely eliminated, but I expect this would be adequate for most applications.

**Comment by snaketron** [comment]
Thank you for the reply, point taken!

To make sure I get the effect of the '-center' flag on the computation of fold-enrichment (equation from manual shown below), I post the following example.

Given:
- 10 external annotations (e.g. enhancers)
- chromatin state that spans 90% of human genome (0.9 * 3 * 10^9 bp) and overlaps all 10 annotations (complete/partial overlap between states and annotations does it matter?)
- human genome size 3*10^9 bp

Calculation:
fold enrichment = (10 bp / 0.9*3*10^9 bp ) / (10 bp / 3*10^9 bp) =  ~ 1.1.

Is this interpretation correct? Are the chromatin states (or contiguous groups of the same chromatin states) also centered somehow?

---------------------------------- from ChromHMM manual -----------------------------------------------------
fold enrichment = (C/A)/(B/D) with:

A: the number of bases in the state 
B: the number of bases in the external annotation
C: the number of bases in the state and the external annotation
D: the number of bases in the genome

**Comment by jernst98** [comment]
Yes the interpretation is correct. Chromatin states are not also centered.

**Comment by snaketron** [comment]
Thanks again!
