### ISSUE TITLE
ConvertGeneTable "main" java.util.NoSuchElementException 

### ISSUE THREAD

**Issue by yussufhajjaj** [jernst98/ChromHMM#35]
Dear all, 

I am trying to creat new CHOORDS and ANCHORFILES from Ensemble Homo_sapiens.GRCh38.103.gtf.gz, but I am getting this error message: Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at edu.mit.compbio.ChromHMM.ConvertGeneTable.convertGeneTableToAnnotations(ConvertGeneTable.java:145)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:15228)
I have checked the previous thread about this issue and it didn't help tbh. I checked the chromsizes file "with ensemble notation", and I don't think the problem doesn't seem from it, I think it's from the gtf file, I opened the ensemble and the UCSC annotation files via R and they seem to be similar, both 9 columns, tab delimited files, and provide the same information, have anyone faced this problem before? Thanks in advance. 

Picture is attached to the error message from the terminal.

![Capture](https://user-images.githubusercontent.com/80690849/111156627-425e5880-8596-11eb-8cec-3fb521ecdbe5.PNG)

**Comment by jernst98** [comment]
As described in the ChromHMM user manual ConvertGeneTable expects a gene table in the format from the UCSC browser format which is not the same format as a gtf file format.

-Jason

**Comment by yussufhajjaj** [comment]
Thanks for the quick reply! so do you think if I convert the .gtf file to .bed or .txt will it solve the problem? sorry for this I'm a bit new to bioinformatics.

**Comment by jernst98** [comment]
Yes, assuming the conversion files the format ChromHMM is expecting for those files.

-Jason

**Comment by yussufhajjaj** [comment]
New error: Exception in thread "main" java.lang.IllegalArgumentException: invalid strand   ENST00000450305
        at edu.mit.compbio.ChromHMM.ConvertGeneTable.convertGeneTableToAnnotations(ConvertGeneTable.java:208)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:15228)

I took a screenshot of the file contents after converting it to .bed format, and its attached. Is that the right format col arrangement?

![Capture2](https://user-images.githubusercontent.com/80690849/111170087-db47a080-85a3-11eb-9796-12fb2850e230.PNG)

**Comment by yussufhajjaj** [comment]
![Capture3](https://user-images.githubusercontent.com/80690849/111171801-8b69d900-85a5-11eb-8e5e-f781821ce423.PNG)
That's the UCSC file. They seem to look almost the same

**Comment by jernst98** [comment]
ConvertGeneTable only takes UCSC gen table format. You can create bed files directly yourself for annotations you are interested and put them in the appropriate COORDS subdirectory and then ChromHMM will use them.

Best,
-Jason

**Comment by yussufhajjaj** [comment]
Dear Jason, 

Hope you are having a good day. 

So what I did is I converted the GTF file from ensemble to .bed and then compared it to the gene table file from UCSC that chromHMM expects and reads. I changed the column formation manually, but I detected a problem in my file that the exonstrt and exonend "multiple sites" are wrong for some reason. I checked all the choords and anchor files and it seems that chromHMM doesn't use them, is my assumption right? Also, for the bins I just added row.names as values, I think chromHMM doesn't use those since they are just indexing values for the browser. Also I added two empty columns at the end because the UCSC table contains information about the protein that ensemble doesn't provide. 

ChromHMM likes the format and it reads it without error messages, but can you please tell me if what I did will provide any bad results in new choords and anchors files? And thanks in advance. 

Attached is a picture of the file I created. Header is "bin, name, chrom, strand, txStart, txEnd, cdsStart, cdsEnd, exonCount, exonStarts "wrong", exonEnds"wrong", emptycolumn1, emptycolumn2"

Also a picture of the UCSC gene table the chromHMM reads.


Best Regards, 

Yussuf


![ensembletoUCSC1](https://user-images.githubusercontent.com/80690849/111300294-371c3300-8651-11eb-8ee6-af0e1e27a24f.PNG)



![ensembletoUCSC](https://user-images.githubusercontent.com/80690849/111299594-6b432400-8650-11eb-863e-88fcde16b373.PNG)

**Comment by jernst98** [comment]
Hi Yussuf,

ChromHMM does use exon start and end information for generating the exon coordinate files.

Best,
-Jason

**Comment by yussufhajjaj** [comment]
So I found this tool provided by UCSC it can change GTF files from ensemble to genePred format that is accepted by chromHMM without any mistakes, the tool is gtfToGenePred, anyone can install it easily with bioconda. 

Bedops won't convert the GTF file from ensemble, and the tool provided by usegalaxy.org will convert it with mistakes. 

Thanks alot for your time and comments Jason, they were very helpful, I really appreciate it.

Attached is a picture of the resulting file.

![genePRED](https://user-images.githubusercontent.com/80690849/111337723-99d3f580-8676-11eb-9a7b-affc5456a835.PNG)

**Comment by jernst98** [comment]
Thanks for letting me know. Note ChromHMM still expects something in the bin column to be present, but doesn't use the value within it.

-Jason
