### ISSUE TITLE
ChromHmm output segment file of varying segment size

### ISSUE THREAD

**Issue by mujahida87** [jernst98/ChromHMM#36]
Hi, I have a question regarding the chromHmm output segment file.
I have used binarization at 200 bp, and my out segments have a minimal length of 200bp but the maximal length is of different sizes. is this normal that software to segment the genomic regions based on enrichment of markers? I was just a bit confused that each replicate produces quite different segment sizes with the same set of parameters and number markers.  

Thank you
![Screenshot 2021-03-25 at 09 29 31](https://user-images.githubusercontent.com/30443593/112442906-a1695d80-8d4c-11eb-80f4-92ec46394486.png)

**Comment by jernst98** [comment]
Yes this is normal. In the segmentation bed file if consecutive 200bp bins are assigned to the same state they are merged to be part of the same interval in the output file. 

ChromHMM has the option to also provide the segmentation in an alternative format with the flag '-printstatebyline'  where each line just contains the state assignment for one 200bp window.

**Comment by mujahida87** [comment]
Thank you very much
