### ISSUE TITLE
Chromatin marks for ChIP seq data

### ISSUE THREAD

**Issue by AIqbal94** [jernst98/ChromHMM#37]
Hi @jernst98 
I have a question about using chromHMM in a standard ChIP seq pipeline (mostly used for determining binding of multiple transcription factors and DNA/mtDNA binding proteins) for the functional annotation of peaks. This might be a very basic question but I am a bit unsure of what marks I should use in the `cellmarkfile.txt`

I tried with all the marks mentioned here: https://static-content.springer.com/esm/art%3A10.1038%2Fnbt.1662/MediaObjects/41587_2010_BFnbt1662_MOESM5_ESM.pdf

but firstly it takes very long to run and secondly I'm not quite sure if all the marks would be relevant in such cases. 

I would really like to know your opinion on this

Thank you.

**Comment by jernst98** [comment]
Are you asking among data you already have which should be included in the ChromHMM model or what data should be prioritized for collection in a new sample?

-Jason

**Comment by AIqbal94** [comment]
Hi @jernst98 
So sorry about the late reply.
My question is more like for example there's a ChIP seq protocol done to determine the binding regions of FOXO tf. Does it make sense to run chromHMM on this ChIPseq data to annotate the peaks and if so, what marks should be used in the BinariseBam step in the `cellmarkfile.txt` file?

**Comment by jernst98** [comment]
If this is for a cell type in which there are already ChromHMM annotations available, you could just use the existing ChromHMM annotations. If you want to learn a new model specifically in the cell type/condition of interest, the set of data to include in the model can depend on the biological question you are interested in, but one reasonable strategy would be to use all the general chromatin marks available to you in that cell type/condition as input to learn a chromatin state model. You can then analyze the FOXO binding in relation to those chromatin states.

-Jason

**Comment by AIqbal94** [comment]
Got it. I will play around with the general chromatin marks available then. 
Thank you so much for your input.
