### ISSUE TITLE
Is there any suitable way to compare the states of different tissue?

### ISSUE THREAD

**Issue by shangguandong1996** [jernst98/ChromHMM#38]
Hi, dear developer

I am wondering whether you can recommend some ways to compare states between different tissue. Now I find some paper will use unionbedg in bedtools to track state between different tissue. But as the tissue number increase, I find the result will be difficult to explain.

Best wishes

Guandong Shang

**Comment by jernst98** [comment]
Hi Guandong,

Some options in general:
* Conduct multiple pairwise comparisons
* Cluster ChromHMM bins (default 200bp intervals) or other loci of interest based on the presence
of specific state(s) of interest across cell type
* Use the stacked modeling approach which learns a single annotation of the genome based on the data
from all the tissue types
Here is a recent example of a large-scale application of that modeling approach:
https://www.biorxiv.org/content/10.1101/2020.11.17.387134v1

Best,
-Jason
