### ISSUE TITLE
Compare with 2 different result

### ISSUE THREAD

**Issue by dahun73** [jernst98/ChromHMM#39]
Hello !

I'm biginer using chromHMM. I'm just curious about how to compare with 2 different result.
Many people want to know how different they are. For example, I'm curious about which chromatin state changes are included after treatment something.

**Comment by jernst98** [comment]
Do you have replicates for with and without treatment or just one of each?

**Comment by dahun73** [comment]
Yes! I have 2 replicates each condition both treatment and untreatment.

**Comment by jernst98** [comment]
One thing you could consider doing is learning a concatenated model based on the four datasets. From this you could then analyze the genome-wide pairwise chromatin state co-assignment enrichments for the four datasets and relate enrichments for pairs of datasets of different conditions compared to what is seen among replicates from the same condition.

**Comment by dahun73** [comment]
Thank you for nice tips! :) I will try what you mentioned.
