### ISSUE TITLE
discrepancy between X_Y_overlap.png and X_Y_overlap.txt

### ISSUE THREAD

**Issue by keksundso** [jernst98/ChromHMM#41]
Hi,
I wanted to redo the overlap plot based on the .txt file output. However, the values do not correlate with the plot. 
E.g. for state 11 the enrichment seems to be higher on TSS2kb compared to the TSS (see image left). However, according to the txt file, the genome value is _30_ and the gene _11_ (se image middle).

Dividing each column by its base value and scaling it all to one (genome column is treated differently) creates a fairly similar plot, however its not identical (e.g the above described difference persists).
 

![Screenshot from 2021-11-12 13-30-52](https://user-images.githubusercontent.com/32193149/141467636-7632dbd0-672f-4111-ade2-59bb628d98d3.png)

So it seems I am either misinterpreting the plot or the table, but I am not sure which one.

**Comment by jernst98** [comment]
ChromHMM by default colors each column on its own color scale. It appears you are using a uniform color scale.
OverlapEnrichment gives the option to use a uniform color scale with the flag '-uniformscale'.

-Jason

**Comment by keksundso** [comment]
thank you very much! That makes sense
