### ISSUE TITLE
nullpointerexception error while running CompareModels 

### ISSUE THREAD

**Issue by SplitInf** [jernst98/ChromHMM#42]
Hi, 

I am getting a nullpointerexception error while running CompareModels and can't quite troubleshoot what is wrong.
This is similar to this issue here (https://github.com/jernst98/ChromHMM/issues/27) but the difference being I am using the emission file generated directly from ChromHMM. 

```
java -mx4000M -jar ChromHMM.jar CompareModels treatment1/results/emissions_8.txt treatment2/results/ 1v2

Exception in thread "main" java.lang.NullPointerException
	at edu.mit.compbio.ChromHMM.StateAnalysis.makeModelEmissionCompare(StateAnalysis.java:3820)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13585)

head treatment1/results/emissions_8.txt
State (Emission order)	mark1	mark2	mark3
1	2.1727870800772254E-72	2.4236493512549204E-47	0.858399716497905
2	6.697771414533143E-102	0.9995916808920738	0.9982136561038701
3	7.62884882600209E-115	0.017388585226759533	2.9595321706205998E-248
4	0.8868409570279551	0.9546918414337829	1.2736435867177494E-166
5	1.0	0.9999999999997488	0.9985053640320722
6	0.9658642491977975	1.2972980770896698E-153	9.23970285249423E-242
7	0.99994958182997	4.055123944305359E-90	0.9951794781672061
8	1.2784797488695767E-211	9.67225807800232E-179	7.774716490529544E-269


```

Thanks!

**Comment by jernst98** [comment]
Does every emissions_* file in  treatment2/results have the same set of mark names as in emissions_8.txt (mark1, mark2, mark3)? 
If not I think that can explain the issue. ChromHMM was assuming there would be the same set of marks for the reference model as the models being compared with.
