### ISSUE TITLE
output truncates chromosomes

### ISSUE THREAD

**Issue by umasstr** [jernst98/ChromHMM#45]
I ran LearnModel on binarized BEDs to completion without error. HTML and dense_BEDs are generated, but the output coordinates are all randomly truncated halfway down the genome. Any help resolving this issue would be appreciated.

![image](https://user-images.githubusercontent.com/44478133/166184162-176b3963-3530-44b5-b7c2-fdc77c96d7d9.png)

![image](https://user-images.githubusercontent.com/44478133/166184420-d8e63d05-11e8-45be-8c88-33d8cf45211c.png)

![image](https://user-images.githubusercontent.com/44478133/166185022-d24860be-3867-46ac-ab1e-7013dfdcf67d.png)

All output BEDs exclude coordinates >100Mb in chr1, e.g.

> $ grep chr1 WT_5_dense.bed | sort -k3,3n | tail
> chr1    99565000        99565600        3       0       .       99565000        99565600        51,255,153
> chr1    99565600        99566000        4       0       .       99565600        99566000        255,255,0
> chr1    99566000        99567200        3       0       .       99566000        99567200        51,255,153
> chr1    99567200        99567400        5       0       .       99567200        99567400        204,0,51
> chr1    99567400        99569400        2       0       .       99567400        99569400        0,102,0
> chr1    99569400        99571400        5       0       .       99569400        99571400        204,0,51
> chr1    99571400        99576800        2       0       .       99571400        99576800        0,102,0
> chr1    99576800        99577400        5       0       .       99576800        99577400        204,0,51
> chr1    99577400        99578600        4       0       .       99577400        99578600        255,255,0
> chr1    99578600        99582400        2       0       .       99578600        99582400        0,102,0

The chromsizes file looks to be correct

> $ cat ../CHROMSIZES/hg38.txt | grep chr1
>chr1    248956422

My input BEDs certainly have coordinates >100Mb.

> $ grep chr1 ../../bed/WT-K27Ac_Apr09.bed | sort -k3,3n | tail
> chr1    248946385       248946422       NB552575:103:HJKCVBGXJ:3:22406:11676:9181/2     0       -
> chr1    248946385       248946422       NB552575:103:HJKCVBGXJ:3:22512:15394:19501/1    0       -
> chr1    248946385       248946422       NB552575:103:HJKCVBGXJ:4:12510:23537:3827/1     0       -
> chr1    248946385       248946422       NB552575:103:HJKCVBGXJ:4:13410:21523:15639/2    0       -
> chr1    248946386       248946422       NB552575:103:HJKCVBGXJ:3:13405:6777:19110/2     0       -
> chr1    248946388       248946422       NB552575:103:HJKCVBGXJ:1:22312:16836:14295/1    0       -
> chr1    248946389       248946422       NB552575:103:HJKCVBGXJ:1:11311:7160:11685/2     0       -
> chr1    248946389       248946422       NB552575:103:HJKCVBGXJ:1:12208:18474:1096/2     0       -
> chr1    248946389       248946422       NB552575:103:HJKCVBGXJ:1:23312:23278:7231/1     0       -
> chr1    248946393       248946422       NB552575:103:HJKCVBGXJ:4:21603:4777:6602/2      18      -

**Comment by jernst98** [comment]
How many lines are in your binarized files for chr1?

Did you add non-default options in the binarization or learn model steps?

**Comment by umasstr** [comment]
Thanks for the quick reply. 

No non-default options as far as I know:
>java -mx12g -jar ChromHMM.jar LearnModel ./binarizedData output01 5 hg38

497K lines for chromosome 1
>497914 WT_chr1_binary.txt

**Comment by jernst98** [comment]
What options did you use to binarize the data?

Based on the number of lines on chr1 I suspect you might have had the option '-b 500' to have 500bp bins instead of the default of 200bp. Is that the case? If so you also need to give the '-b 500' option to LearnModel.

**Comment by umasstr** [comment]
I checked my history and you're correct. Apologies for my oversight, and thank you so much for your help.
