### ISSUE TITLE
model_N.txt file clarification

### ISSUE THREAD

**Issue by NMaziak** [jernst98/ChromHMM#51]
https://github.com/jernst98/ChromHMM/issues/30 This is continuing on the lines of this thread. I was just wondering what the second and fifth value mean of the first line. Sorry if this is very obvious or that I keep missing this information. 

Thanks again for a wonderful tool!
Noura

**Comment by jernst98** [comment]
The value is the number of input marks. The fifth value is the number of EM iterations.
