### ISSUE TITLE
OverlapEnrichment in LearnModel and standalone gives different results

### ISSUE THREAD

**Issue by isidorabi** [jernst98/ChromHMM#52]
Hi, 
I've noticed the results of the overlap enrichment are different (both in the .txt and the heatmap) depending on whether the command is run separately from LearnModel or inside it, with the same annotations provided (and correct assembly specified in LearnModel). 
Do you have any info on this?

code: 
`java -mx5000M -jar ${ChromHMM}/ChromHMM.jar LearnModel -b ${binsize} -gzip -i out_01 -printposterior -printstatebyline -u ${COORDS} ${OUTDIR_BIN} ${out} ${st} hg38`  (`$COORDS` is COORDS_naive)

or

`java -mx5000M -jar ${ChromHMM}/ChromHMM.jar OverlapEnrichment -b ${binsize} -multicount ${out}/*_segments.bed.gz ${annot} Naive_${st}_out_01_onlygradient` (`$annot` is COORDS_naive/hg38)

Please see the results attached (first one corresponding to the first code, second one to the second).

Thanks!
![insideLearnModel](https://user-images.githubusercontent.com/114924428/233656245-eb2427ae-8b27-4150-a3c8-f464d66f03fe.png)
![standalone](https://user-images.githubusercontent.com/114924428/233656264-10deaa9d-fb57-4167-8f79-91848005827d.png)

**Comment by jernst98** [comment]
You have the '-multicount' flag present for OverlapEnrichment. LearnModel calls OverlapEnrichment without the '-multicount' flag.  Do you get the same enrichments if you remove the '-multicount' flag from OverlapEnrichment?

**Comment by isidorabi** [comment]
Yes I do! Thanks.
