### ISSUE TITLE
Only the first 10% of the contigs outputted

### ISSUE THREAD

**Issue by johannesnicolaus** [jernst98/ChromHMM#53]
Hi, I successfully ran Chromhmm, however I realized that the results only included the first 10% of chromosomes. I checked the chromosome lengths file and it is correct. 

Are the results downscaled by a factor of 10? Or is this a bug?

**Comment by jernst98** [comment]
If there are no reads mapping to a chromosome then ChromHMM does not produce binarized data for it. Is that what is happening in your case?

**Comment by johannesnicolaus** [comment]
Thanks for the super quick reply! Sorry I think it's because I did not set the binsize `-b` when I ran `BinarizeBam`. I will run it again and will close this issue if it works.
