### ISSUE TITLE
chromHMM input choice and annotation of external bed file

### ISSUE THREAD

**Issue by cleliacort** [jernst98/ChromHMM#54]
Hi, 

I am using chromHMM with histone modification related to tumour sample(multiple myeloma) and two times where the cell acquired drug resistance, coming from two different cell lines.

My aim would be make a model able to annotate the state of specific tumour region. From what I have read, using all the histone modifications together would enhance the accuracy of the model (for me, this means that I can define states with biological significance.).

In the model I've developed, I have incorporated all the histone modifications associated with both cell lines.However, I have some concerns about enhancing the model's reliability and effectively using it to annotate external BED files.

I have access to publicly available histone modification data for peripheral blood (PB) at different states, including memory and germinal states, obtained from tonsil and bone marrow samples. I'm considering integrating these data with my existing dataset. Can this integration offer any advantages, and if so, what are they?

Now, let's assume I've created an ideal model and obtained segment files with state annotations for each cell passed as input. My goal is to annotate an external BED file, and my initial thought is to use bedtools to perform an overlap analysis. However, I have some questions about this procedure: 1)Which segment file should I use for annotating my external file? 2)What is the best practice for the overlap analysis? Should I ensure that at least half of the external BED file region overlaps with the regions in the segment file, or is there a different criterion I should follow?

Thanks in advance for the help and your time!

**Comment by jernst98** [comment]
ChromHMM can model data from different cell types or conditions either in a concatenated approach where there is a single annotation per cell/condition type or with a stacked approach where there is a single annotation of the genome based on all the data.

Whether it makes sense to integrate public data into the model learning will depend on the specifics of the situation. One consideration is whether technical batch effect differences will dominate the biological differences you are trying to detect. One can also use external data for enrichment analyses after a model is learned.

The four column (non-browser) segment file should be used for enrichment analyses.  ChromHMM has an OverlapEnrichment command that supports enrichment analyses. If you are using ChromHMM to annotate the entire genome then every position should be in the segment except possibly the very end of the chromosome that forms an incomplete bin . If you are using ChromHMM to annotate only a subset of chromosomes it is possible the situtation will be different.
