### ISSUE TITLE
Base from OverlapEnrichment command

### ISSUE THREAD

**Issue by hanrong498** [jernst98/ChromHMM#55]
Hi!

Thanks for this tool! I have a question regarding the output txt file of the OverlapEnrichment command. Could you explain what is the row `base` here? Thanks!!

```
State (Emission order)	Genome %	CpGIsland.hg18.bed.gz	RefSeqExon.hg18.bed.gz	RefSeqGene.hg18.bed.gz	RefSeqTES.hg18.bed.gz	RefSeqTSS.hg18.bed.gz	RefSeqTSS2kb.hg18.bed.gz	laminB1lads.hg18.bed.gz
1	0.62520	22.34920	3.54763	1.12031	1.80571	16.66296	8.63139	0.48091
2	1.61455	25.26849	5.04580	1.45672	3.79054	22.35982	13.33136	0.15525
3	1.21218	0.49769	1.62770	1.25788	2.10774	1.74437	2.95730	0.26333
4	3.64100	0.48975	0.99152	1.14644	1.30553	1.26064	1.97917	0.34405
5	1.09957	0.40899	3.71355	1.87522	3.89067	0.98496	1.63125	0.19019
6	6.93153	0.35103	3.30689	2.03147	2.77736	0.34970	0.57022	0.18741
7	0.17508	0.00000	0.94979	0.36807	1.01812	0.88370	0.76537	1.08844
8	0.92851	2.44518	1.83440	1.04085	1.40784	1.88849	1.75795	0.57553
9	70.35943	0.30439	0.56818	0.84463	0.63168	0.36210	0.50925	1.25596
10	13.41295	1.21326	1.13327	1.09200	1.19164	1.18426	1.41249	0.54242
Base	100	0.7720074495	3.1219184216	45.8081474308	0.0012517460	0.0014421482	4.6551034494	45.6643015138

```

Best,
Hanrong

**Comment by jernst98** [comment]
The values in row corresponds to the percentage of the genome the annotation of the column covers.

**Comment by hanrong498** [comment]
Thank you for the explanation!

**Comment by hanrong498** [comment]
Thank you for the explanation! 

More specifically, I want to ask what the "base" state refers to?


Thanks!
Hanrong

**Comment by hanrong498** [comment]
Thanks for the explanation and sorry for spamming from closing and re-openning. 

Referring to what mentioned in [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5945550/):

> The last row indicates the % of the genome each external annotation covers. 

Does it mean that in this example, <1% of genomes are CpGIsland, ~3% are exons and so on?

**Comment by jernst98** [comment]
Yes.
