### ISSUE TITLE
Reorder genomic annotations and TSS neighborhood

### ISSUE THREAD

**Issue by jmzvillarreal** [jernst98/ChromHMM#57]
Hi,
Thanks for this cool tool.
I am reordering the states of the model and the columns of the emission matrix in order to generate a comparative figure.
How can I obtain the heatmaps for genomic annotations and TSS in the same order ?
Thanks in advance,
Best.
Jaime.

**Comment by jernst98** [comment]
Hi Jaime,

To reorder the heatmaps for the genomic annotations you need to run OverlapEnrichment after the segmentation file has been reordered. The -r option of Reorder allows you to produce a segmentation file with the states reordered. Alternatively if you have a reordered model, you can run MakeSegmentation and then supply that segmentation file to OverlapEnrichment.

Best,
-Jason

**Comment by jmzvillarreal** [comment]
Thank you very much  Jason. It worked fine !
Jaime.
