### ISSUE TITLE
Abnormal annotation at the end of some chromosomes when using LearnModel command

### ISSUE THREAD

**Issue by bio-lilin** [jernst98/ChromHMM#58]
Hi, dear developers
Thank you for developing such a great tool! When I used the 'LearnModel' command to annotate the genome state of a cell line, I  found abnormal annotation at the end of some chromosomes. The error was that the start sites were less than the end sites and all the regions were annotated as 'TssFlnk'. I feel very confused about this error. And is it suitable to delete the abnormal regions directly?
Best wishes
Lin Li
![abnormal regions](https://github.com/jernst98/ChromHMM/assets/75014744/daab232e-81c3-426b-885f-a246f5deac07)

**Comment by bio-lilin** [comment]
Thanks for your quick reply, Jason. Your guess was right. I corrected this option and it worked.
Best,
Lin Li

**Comment by IqRaZaFaR16** [comment]
@bio-lilin could you please help how i can assign 12 state 
while im using this command i got an error 
i have merged uniquely aligned peaks files for each replicates of sample into one .bed file per sample then generate file cellmarkfiletable_hg38.txt cellmarkfiletable_hg38.txt

<h5>after this i have used to binazriedbed file via using this command:</h5>
java -mx4000M -jar /home/data/iqra/H4K16ac/H9/bamtobed/merged_peaks/ChromHMM/ChromHMM-master/ChromHMM.jar BinarizeBed /home/data/iqra/H4K16ac/H9/bamtobed/hg38.chrom.sizes /home/data/iqra/H4K16ac/H9/bamtobed/merged_peaks /home/data/iqra/H4K16ac/H9/bamtobed/chromHmm/cellmarkfiletable_hg38.txt /home/data/iqra/H4K16ac/H9/bamtobed/chromHmm/outputsignaldir

then used
$java -mx8000M -jar /home/data/iqra/H4K16ac/H9/bamtobed/merged_peaks/ChromHMM/ChromHMM-master/ChromHMM.jar LearnModel -p 4 -l /home/data/iqra/H4K16ac/H9/bamtobed/hg38.chrom.sizes /home/data/iqra/H4K16ac/H9/bamtobed/chromHmm/outputsignaldir /home/data/iqra/H4K16ac/H9/bamtobed/chromHmm/chromatin_states 5 hg38

im trying to reanalyzed paper data and generated a reference plot as they have generated
emissions_5.txt a, Bar chart showing the percentage distribution (y axis) of histone PTMs CUT&Tag peaks across ChromHMM chromatin features. Low signal (Lo), transcription (Txn)

could you please guide me how i can annotate these states. while using this i got an error (bioinformatics) iqra@bio-Super-Server:~/H4K16ac/H9/bamtobed/merged_peaks$ java -mx8000M -jar /home/data/iqra/H4K16ac/H9/bamtobed/merged_peaks/ChromHMM/ChromHMM-master/ChromHMM.jar LearnModel \

-p 0 -l /home/data/iqra/H4K16ac/H9/bamtobed/hg38.chrom.sizes -init RANDOM /home/data/iqra/H4K16ac/H9/bamtobed/chromHmm/outputsignaldir /home/data/iqra/H4K16ac/H9/bamtobed/chromHmm/chromatin_states 10 hg38 usage: LearnModel [-b binsize][-color r,g,b][-d convergedelta][-e loadsmoothemission][-f inputfilelist][-gzip][-h informationsmooth][-holdcolumnorder][-holdroworder][-i outfileID][-init information|random|load][-l chromosomelengthfile][-lowmem][-m modelinitialfile][-many][-n numseq][-noautoopen][-nobed][-nobrowser][-nobrowserheader][-noenrich][-noimage][-nopseudolast][-p maxprocessors][-pseudo][-printposterior][-printstatebyline][-r maxiterations][-s seed][-scalebeta][-splitrows][-stateordering emission|transition][-t loadsmoothtransition][-u coorddir][-v anchorfiledir][-x maxseconds][-z zerotransitionpower] inputdir outputdir numstates assembly (bioinformatics) iqra@bio-Super-Server:~/H4K16ac/H9/bamtobed/merged_peaks$

**Comment by jernst98** [comment]
This was responded to in #62
