### ISSUE TITLE
On this data the INFORMATION initialization strategy can only support 4 states

### ISSUE THREAD

**Issue by LHXqwq** [jernst98/ChromHMM#59]
When I run the following command:

java -mx1600M -jar ChromHMM.jar LearnModel -b 200 Input_FC2 Output_FC2_10 10 hg19

I encountered the following error. What could be the potential issue?

Exception in thread "main" java.lang.IllegalArgumentException: On this data the INFORMATION initialization strategy can only support 4 states. Check if the binarization was done correctly, and if so use the RANDOM or LOAD options for more states
	at edu.mit.compbio.ChromHMM.ChromHMM.informationInitializeNested(ChromHMM.java:2675)
	at edu.mit.compbio.ChromHMM.ChromHMM.buildModel(ChromHMM.java:1036)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:15223)

**Comment by jernst98** [comment]
Do you only have 2 input marks? The default initialization mode can only handle 2^(number of input mark) states but you are asking for 10 states

**Comment by LHXqwq** [comment]
Yes, I currently only have data for H3K4me3 and H3K27ac. Can ChromHMM be used to roughly identify enhancers and promoters based solely on these two datasets?

**Comment by jernst98** [comment]
Yes. You would need to either use at most 4 states or if using more than 4 states use the '-init random' flag

**Comment by LHXqwq** [comment]
When I run java -mx1600M -jar ChromHMM.jar LearnModel -b 200 Input_FC2 Output_FC2_4 4 ss11, the following error occurs:

Writing to file Output_FC2_4_2/ss11_4_segments.bed
Writing to file Output_FC2_4_2/ss11_4_dense.bed
Writing to file Output_FC2_4_2/ss11_4_expanded.bed
Writing to file Output_FC2_4_2/ss11_4_overlap.txt
Writing to file Output_FC2_4_2/ss11_4_overlap.png
Writing to file Output_FC2_4_2/ss11_4_overlap.svg
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:642)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at edu.mit.compbio.ChromHMM.StateAnalysis.neighborhoodMax(StateAnalysis.java:2942)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:15459)
	
What could be the cause? I did not find the '-' character in the files under the Input_FC2 folder.

**Comment by jernst98** [comment]
I think there is a '-' in a file in the ss11 folder of ANCHORFILES. Did you check there?

**Comment by LHXqwq** [comment]
Thank you very much. The issue was with a file in the ss11 folder of ANCHORFILES where there was a space in the second column. I have now successfully run the process and obtained the corresponding results.

The contents of emissions_4.txt are as follows:：
State (Emission order)	H3K27ac	H3K4me3
1	0.7371722491995913	0.025454951706880308
2	0.0070734777583484985	2.808219552645712E-4
3	0.9531553476199173	0.9489478579210275
4	0.0526273184047077	0.8673363187489265

In the ss11_4_expanded.bed file, I noticed the following correspondence between state and color:
State	color
1	0,0,255
2	0,102,0
3	51,255,153
4	255,255,0

Could you please tell me which of the 15 states these 4 states correspond to? For example (Active Promoter, Weak Promoter, Strong Enhancer, Weak/Poised Enhancer, etc.).

**Comment by jernst98** [comment]
Have you run enrichments for annotated TSS/promoter regions?

**Comment by jernst98** [comment]
I find it odd that you are not seeing TSS enrichment in state 4 associated with H3K4me3. You might want to double check the emission parameters correspond to the final version of the model the enrichments are based on and/or your H3K4me3 data is ok.
