### ISSUE TITLE
Warning did not find data 

### ISSUE THREAD

**Issue by Zefeng-Wu** [jernst98/ChromHMM#6]
I use my own data to perform BinarizeBam with the command"
java -jar ~/opt/softs/ChromHMM/ChromHMM.jar BinarizeBam -o ../3ChroHMM/ ../tair.genome  ./  cellmarkfiletable ../3ChroHMM/"
but it gave the warnings as followings:
Warning did not find data for leaf  H3K27ac treating as missing
Warning did not find data for leaf  H3K27me3 treating as missing
Warning did not find data for leaf  H3K36ac treating as missing
Warning did not find data for leaf  H3K36me3 treating as missing
Warning did not find data for leaf  H3K4me1 treating as missing
Warning did not find data for leaf  H3K4me2 treating as missing
Warning did not find data for leaf  H3K4me3 treating as missing
Warning did not find data for leaf  H3K9ac treating as missing
Warning did not find data for leaf  H3K9me2 treating as missing
Writing to file ../3ChroHMM//leaf _Pt_binary.txt
Writing to file ../3ChroHMM//leaf _Mt_binary.txt
Writing to file ../3ChroHMM//leaf _4_binary.txt
Writing to file ../3ChroHMM//leaf _2_binary.txt
Writing to file ../3ChroHMM//leaf _3_binary.txt
Writing to file ../3ChroHMM//leaf _5_binary.txt
Writing to file ../3ChroHMM//leaf _1_binary.txt
Warning did not find data for leaf H3K27me1 treating as missing
Warning did not find control data for leaf H3K27ac treating as missing
Warning did not find control data for leaf H3K27me1 treating as missing
Warning did not find control data for leaf H3K36me3 treating as missing
Warning did not find control data for leaf H3K4me1 treating as missing
Writing to file ../3ChroHMM//leaf_Pt_controlsignal.txt
Writing to file ../3ChroHMM//leaf_Mt_controlsignal.txt
Writing to file ../3ChroHMM//leaf_4_controlsignal.txt
Writing to file ../3ChroHMM//leaf_2_controlsignal.txt
Writing to file ../3ChroHMM//leaf_3_controlsignal.txt
Writing to file ../3ChroHMM//leaf_5_controlsignal.txt
Writing to file ../3ChroHMM//leaf_1_controlsignal.txt
Writing to file ../3ChroHMM//leaf_Pt_binary.txt
Writing to file ../3ChroHMM//leaf_Mt_binary.txt
Writing to file ../3ChroHMM//leaf_4_binary.txt
Writing to file ../3ChroHMM//leaf_2_binary.txt
Writing to file ../3ChroHMM//leaf_3_binary.txt
Writing to file ../3ChroHMM//leaf_5_binary.txt
Writing to file ../3ChroHMM//leaf_1_binary.txt

My cell files are as followings: (some marks have no control files with no fourth columns):
$ less cellmarkfiletable 
leaf    H3K4me1 H3K4me1.bam
leaf    H3K4me2 H3K4me2.bam     H3K4me3_H3K4me2.input.bam
leaf    H3K4me3 H3K4me3.bam     H3K4me3_H3K4me2.input.bam
leaf    H3K9ac  H3K9ac.bam      H3K9ac.input.bam
leaf    H3K9me2 H3K9me2.bam     H3K9me2_H3K27me3.input.bam
leaf    H3K27ac H3K27ac.bam
leaf    H3K27me1        H3K27me1.bam
leaf    H3K27me3        H3K27me3.bam    H3K9me2_H3K27me3.input.bam
leaf    H3K36ac H3K36ac.bam     H3K36ac.input.bam
leaf    H3K36me3        H3K36me3.bam

my marks file is as followings:
$ ls
cellmarkfiletable  H3K27me1.bam  H3K27me3.ni.bam  H3K36ac.input.bam  H3K4me1.bam  H3K4me3.bam                H3K9ac.bam        H3K9me2.bam
H3K27ac.bam        H3K27me3.bam  H3K36ac.bam      H3K36me3.bam       H3K4me2.bam  H3K4me3_H3K4me2.input.bam  H3K9ac.input.bam  H3K9me2_H3K27me3.input.bam

**Comment by ernstlab** [comment]
Can you verify to make sure that all of your 'leaf' entries are immediately followed by a tab without a space after them?
That ChromHMM is writing to a file 'leaf _4_binary.txt' suggests there is a file name 'leaf ' with a space after it for some entries.

-Jason

**Comment by Zefeng-Wu** [comment]
Hi, 
Thanks for your reply, and i have solved the problem, but i just met another problem that when i running "binarizebam" , it gave warrning information like:

Warning did not find control data for leaf H3K27ac treating as missing
Warning did not find control data for leaf H3K27me1 treating as missing
Warning did not find control data for leaf H3K36me3 treating as missing
Warning did not find control data for leaf H3K4me1 treating as missing
Writing to file ../3ChroHMM//leaf_Pt_controlsignal.txt
Writing to file ../3ChroHMM//leaf_Mt_controlsignal.txt
Writing to file ../3ChroHMM//leaf_4_controlsignal.txt
Writing to file ../3ChroHMM//leaf_2_controlsignal.txt
Writing to file ../3ChroHMM//leaf_3_controlsignal.txt
Writing to file ../3ChroHMM//leaf_5_controlsignal.txt
Writing to file ../3ChroHMM//leaf_1_controlsignal.txt
Writing to file ../3ChroHMM//leaf_Pt_binary.txt
Writing to file ../3ChroHMM//leaf_Mt_binary.txt
Writing to file ../3ChroHMM//leaf_4_binary.txt
Writing to file ../3ChroHMM//leaf_2_binary.txt
Writing to file ../3ChroHMM//leaf_3_binary.txt
Writing to file ../3ChroHMM//leaf_5_binary.txt
Writing to file ../3ChroHMM//leaf_1_binary.txt

Then i checked the output file , for example the file "leaf_1_binary.txt", i found the column of histone mark without control sample are nearly all "1" rather than "0" or "1" in the column. My cellmarksfile (tab separation) is:


leaf	H3K4me2	H3K4me2.bam	H3K4me2.input.bam
leaf	H3K4me3	H3K4me3.bam	H3K4me3.input.bam
leaf	H3K9ac	H3K9ac.bam	H3K9ac.input.bam
leaf	H3K9me2	H3K9me2.bam	H3K9me2.input.bam
leaf	H3K27me3	H3K27me3.bam	H3K27me3.input.bam
leaf	H3K36ac	H3K36ac.bam	H3K36ac.input.bam
leaf	H3K27me1	H3K27me1.bam
leaf	H3K27ac	H3K27ac.bam
leaf	H3K36me3	H3K36me3.bam
leaf	H3K4me1	H3K4me1.bam

How to solve this problem? Should i make two "cellmarksfile" files to bambinarize these bam files with and without input sample respectively and then merge them together? Thanks!

**Comment by ernstlab** [comment]
Hi Zefeng,

Thanks for bringing this to my attention. 
I fixed a bug in the new version of ChromHMM (v1.14), 
which is now on the ChromHMM website.
You should get normal output if you run it all at once with the
new version. Please let me know if it does not fix the issue.

Thanks,
-Jason

**Comment by Zefeng-Wu** [comment]
Thanks for your reply, it seems to produce normal result after updating to the newest version.
