### ISSUE TITLE
Is equal read depth necessary?

### ISSUE THREAD

**Issue by jma1991** [jernst98/ChromHMM#7]
Is it recommended to down-sample the input BAM/BED files to the same sequencing depth before running ChromHMM?

**Comment by ernstlab** [comment]
If you are just considering different marks in the same cell type, then that is usually not recommended. If you are asking about the same mark across different samples and your focus is on comparing the samples, then that can make sense particularly if there are large differences in read depth that would confound the comparisons.

-Jason
